version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    image: naviq-ai-web:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - api

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: naviq-ai-api:latest
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
